## 8.1 예외처리

### 프로그램 오류
프로그램 오류는 발생시점에 따라 '컴파일 에러(compile-time error)'와 '런타임 에러(runtime error)'로 나눌 수 있다.
글자 그대로 '컴파일 에러'는 컴파일 할 때 발생하는 에러이고 프로그램의 실행도중에 발생하는 에러를 '런타임 에러'라고 한다.
이 외에도 '논리적 에러(logical error)'가 있는데, 컴파일도 잘되고 실행도 잘되지만 의도한 것과 다르게 동작하는 것을 말한다.<br>
<br>
소스코드를 컴파일하면 컴파일러가 소스코드(&#42;.java)에 대해 오타나 잘못된 구문, 자료형 체크 등의 기본적인 검사를 수행하여 오류가 있는지를 알려준다.
컴파일러가 알려 준 에러들을 모두 수정해서 컴파일을 성공적으로 마치고 나면, 클래스 파일(&#42;.class)이 생성되고, 생성된 클래스 파일을 실행할 수 있게
되는 것이다.<br>
<br>
컴파일을 성공적으로 마쳐도 에러가 발생할 수 있다. 컴파일러가 소스코드의 기본적인 사항은 컴파일 시에 모두 걸러주지만, 실행도중 발생할 수 있는
잠재적인 오류까지 검사할 수 없기 때문이다. 예를 들면 프로그램이 실행 중 동작을 멈춘 상태로 오랜시간 지속되거나, 갑자기 프로그램이 실행을
멈추고 종료되는 경우 등이 이에 해당한다.<br>
<br>
***런타임 에러를 방지하기 위해서는 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에 대한 대비를 하는 것이 필요하다.***<br>
자바에서는 실행시(runtime) 발생할 수 있는 프로그램 오류를 '에러(error)'와 '예외(exception)', 두 가지로 구분하였다. 에러는 메모리 부족(OutOfMemoryError)이나
스택오버플로우(StackOverflowError)와 같이 일단 발생하면 복구할 수 없는 심각한 오류이고, 예외는 발생하더라도 수습될 수 있는 비교적 덜 심각한 것이다.<br>
<br>
에러가 발생하면, 프로그램의 비정상적인 종료를 막을 길이 없지만, 예외는 발생하더라도 프로그래머가 이에 대한 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료를
막을 수 있다.

    에러(error)       프로그램 코드에 의해서 수습될 수 없는 심각한 오류
    예외(exception)   프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

### 예외 클래스의 계층구조
자바에서는 실행 시 발생할 수 있는 오류(Exception과 Error)를 클래스로 정의하였다. 앞서 배운 것처럼 모든 클래스의 조상은 Object클래스이므로
Exception과 Error클래스 역시 Object클래스의 자손들이다.

<figure>
    <img src="https://velog.velcdn.com/images/mingseok/post/55d9e691-cea8-4add-8859-327a9c1e4521/image.png">
</figure>

모든 예외의 최고 조상은 Exception클래스이며, 상속계층도를 Exception클래스부터 도식화하면 다음과 같다.

<figure>
    <img src="https://images.velog.io/images/kookiencream/post/44938894-584d-4ee5-9733-4903e956d49f/java_image_121.png">
</figure>

위 그림에서 볼 수 있듯이 예외 클래스들은 다음과 같이 두 그룹으로 나눠질 수 있다.
1. Exception클래스와 그 자손들(그림의 윗부분, RuntimeException과 자손들 제외)
2. RuntimeException클래스와 그 자손들(그림의 아랫부분)

앞으로 RuntimeException클래스와 그 자손 클래스들을 'RuntimeException클래스들'이라 하고, RuntimeException클래스들을 제외한 나머지 클래스들을
'Exception클래스들'이라 하겠다.<br>
<br>
***RuntimeException***클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다. 예를 들면, 배열의 범위를
벗어난다던가(ArrayIndexOutOfBoundsException), 값이 null인 참조변수의 멤버를 호출하려 했다던가(NullPointerException), 클래스간의
형변환을 잘못했다던가(ClassCastException), 정수를 0으로 나누려고(ArithmeticException)하는 경우에 발생한다.<br>
<br>
***Exception***클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로서, 프로그램의 사용자들의 동작에 의해서 발생하는 경우가 많다. 예를 들면, 존재하지
않는 파일의 이름을 입력했다던가(FileNotFoundException), 실수로 클래스의 이름을 잘못 적었다던가(ClassNotFoundException), 또는 입력한 데이터 형식이
잘못된(DataFormatException)경우에 발생한다.
1. Exception클래스들 : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
2. RuntimeException클래스들 : 프로그래머의 실수로 발생하는 예외

### 예외처리하기 - try - catch문
프로그램의 실행도중에 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머가 이에 대한 처리를 미리 해주어야 한다. 예외처리란, 프로그램 실행시  발생할 수 있는
예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고,
정상적인 실행상태를 유지할 수 있도록 하는 것이다.<br>
예외를 처리하기 위해서는 try-catch문을 사용하며, 그 구조는 다음과 같다.
```java
try {
    // 예외가 발생할 가능성이 있는 문장들을 넣는다.    
} catch (Exception1 e1) {
    // Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.    
} catch (Exception2 e2) {
    // Exception2이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.    
} catch (Exception3 e3) {
    // Exception3이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.    
}
```
하나의 try블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 ***발생한 예외의 종류와 일치하는 단 한개의
catch블럭만 수행된다.*** 발생한 예외의 종류와 일치하는 catch블럭이 없으면 예외는 처리되지 않는다.

```java
class ExceptionEx1 {
    public static void main(String[] args) {
        try {
            try {   } catch(Exception e) {  }
        } catch(Exception e) {
            try {   } catch(Exception e) {  }   // 에러. 변수 e가 중복선언되었다.
        }   // try-catch의 끝
        
        try {
            
        } catch(Exception e) {
            
        } // try-catch의 끝
    }   // main메서드의 끝
}
```

위의 예제는 아무일도 하지 않는다. 단순히 try-catch문의 사용예를 보여주기 위해서 작성한 코드이다. 이처럼 하나의 메서드 내에 여러개의 try-catch문이
사용될 수 있으며, try블럭 또는 catch블럭에 또 다른 try-catch문이 포함될 수 있다. catch블럭 내의 코드에서도 예외가 발생할 수 있기 때문이다. catch블럭의 괄호 내에 선언된 변수는
catch블럭 내에서만 유효하기 때문에, 위의 모든 catch블럭에 참조변수 'e'하나 만을 사용해도 된다.<br>
그러나 catch블럭 내에 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참조변수를 사용해서는 안된다. 각 catch블럭에 선언된 두 참조변수의 영역이 서로 겹치므로 다른 이름을 사용해야만 
서로 구별되기 때문이다.<br>
따라서 위의 예제에서 catch블럭 내의 try-catch문에 선언되어 있는 참조변수의 이름을 'e'가 아닌 다른 것으로 바꿔야 한다.

